# https://jekyllrb.com/docs/configuration/default/


title: vec2pt
author: vlmarch
phone: ""
email: "vec2pt@outlook.com"
source: ./
baseurl: ""
url: "https://vlmarch.github.io"
description: vlmarch Personal Website


github_username: vlmarch
linkedin_username: vladyslav-m
vimeo_username: vec2pt


theme: null
timezone: Europe/Warsaw
date_format: "%Y"

markdown: kramdown
highlighter: rouge

sass:
  sass_dir: _sass
  style: compressed

# plugins:
#   - jekyll-feed
#   - jekyll-seo-tag

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - LICENSE
  - README.md
  - TODO.md

defaults:
  -
    scope:
      type: posts
    values:
      layout: post
      permalink: ./projects/:title:output_ext
